/*  Basic question  */

export const BASIC_QUESTION_TITLE_EXAMPLE = "Film"
export const BASIC_QUESTION_TITLE_MAX_LENGTH = 100

export const BASIC_QUESTION_ANSWER_EXAMPLE = "Can You Hear The Music"
export const BASIC_QUESTION_ANSWER_MAX_LENGTH = 50

export const BASIC_QUESTION_SOURCE_EXAMPLE = "Oppenheimer"
export const BASIC_QUESTION_SOURCE_MAX_LENGTH = 75

export const BASIC_QUESTION_DEFAULT_REWARD = 1

export const BASIC_QUESTION_THINKING_TIME = 15
